# Default configuration for deep learning projects

# Data settings
data:
  batch_size: 32
  num_workers: 4
  train_val_split: 0.8
  seed: 42

# Model settings
model:
  name: "default_model"
  learning_rate: 0.001
  weight_decay: 0.0001
  optimizer: "adam"
  scheduler: "cosine"

# Training settings
training:
  max_epochs: 100
  early_stopping_patience: 10
  gradient_clip_val: 1.0
  precision: 32
  accelerator: "auto"
  devices: "auto"

# Logging settings
logging:
  wandb:
    project: "dl-project"
    entity: null  # Set your wandb username/team
    log_model: true
  tensorboard:
    log_dir: "tensorboard" 